name: mirage_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  mirage:
    path: ../
  mockito: ^5.4.5
  riverpod_annotation: ^2.6.1
  test: ^1.25.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
