builders:
  flumepod:
    import: "package:flumepod/src/builder.dart"
    builder_factories: ["buildFlumepod"]
    build_extensions: {".dart": [".flumepod.dart", ".debug.flumepod.dart"]}
    build_to: source
    auto_apply: dependents
    defaults:
      generate_for: ["test/**"]
    applies_builders: ["riverpod_generator|riverpod_generator"]