name: flumepod
description: "A code generator to create Mockito compliant mocks of Riverpod Notifiers."
repository: https://github.com/Apadmi-Engineering/mirage
issue_tracker: https://github.com/Apadmi-Engineering/mirage/issues
version: 1.0.0
topics:
  - riverpod
  - testing
  - mocking

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.4
  mockito: ^5.4.5
  riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  analyzer: ^9.0.0
  source_gen: ^4.2.0
  dart_style: ^3.0.1
  code_builder: ^4.10.0

  # Testing
  test: ^1.25.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  meta: ^1.16.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.13
  # Testing
  build_test: ^3.3.3
  melos: ^7.5.1

melos:
  useRootAsPackage: true