name: mirage
description: "A code generator to create Mockito compliant mocks of Riverpod Notifiers."
publish_to: "none"
version: 0.4.1

environment:
  sdk: ^3.6.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.2
  mockito: ^5.4.5
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  analyzer: ^7.3.0
  source_gen: ^2.0.0
  dart_style: ^3.0.1
  code_builder: ^4.10.0

  # Testing
  test: ^1.25.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  # Testing
  build_test: ^2.2.2
