// DO NOT MODIFY BY HAND! This file has been generated by Flumepod. If there is an issue with it please raise an issue at: https://github.com/Apadmi-Engineering/mirage/issues

// ignore_for_file: invalid_use_of_internal_member, unused_element

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:riverpod/src/providers/notifier.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'input.dart' as _i3;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i4;
import 'asset:flumepod/test/model.dart' as _i5;
import 'package:riverpod/src/framework.dart' as _i6;
import 'model.dart' as _i7;
import 'package:mockito/src/dummies.dart' as _i8;
import 'dart:async' as _i9;
import 'asset:flumepod/test/input.dart' as _i10;
import 'package:riverpod/misc.dart' as _i11;
import 'package:riverpod/riverpod.dart' as _i12;

// Flumepod generated mock of class [TestNotifier].
class MockTestNotifier extends _i1.$Notifier<String>
    with _i2.Mock
    implements _i3.TestNotifier {
  MockTestNotifier(this.seedBuilder);

  late final _$args = ref.$arg as _i5.Model;

  String Function() seedBuilder;

  get param => _$args;

  @override
  runBuild() {
    {
      final ref = this.ref as _i6.$Ref<String, String>;
      final element = ref.element as _i6.$ClassProviderElement<
          _i6.AnyNotifier<String, String>, String, Object?, Object?>;
      element.handleCreate(ref, () => build(_$args));
    }
  }

  @override
  String build(_i7.Model? param) {
    // keepAlive() used so mock instance with stubbed/real calls isn't disposed.
    ref.keepAlive();
    return noSuchMethod(Invocation.method(#build, [param]),
        returnValueForMissingStub: seedBuilder());
  }

  @override
  String someMethod() {
    return noSuchMethod(
      Invocation.method(#someMethod, []),
      returnValueForMissingStub:
          _i8.dummyValue<String>(this, Invocation.method(#someMethod, [])),
      returnValue:
          _i8.dummyValue<String>(this, Invocation.method(#someMethod, [])),
    );
  }

  @override
  _i9.Future<int> someAsyncMethod() async {
    return noSuchMethod(
      Invocation.method(#someAsyncMethod, []),
      returnValueForMissingStub:
          _i8.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
      returnValue:
          _i8.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
    );
  }

  @override
  void sideEffect() {
    return noSuchMethod(
      Invocation.method(#sideEffect, []),
    );
  }

  @override
  _i9.Future<void> asyncSideEffect() async {
    return noSuchMethod(
      Invocation.method(#asyncSideEffect, []),
    );
  }
}

extension MockTestNotifierAccessor on _i10.TestNotifierProvider {
  _i11.ProviderListenable<MockTestNotifier> get mock {
    return notifier.select((it) => it as MockTestNotifier);
  }
}
