// DO NOT MODIFY BY HAND! This file has been generated by Flumepod. If there is an issue with it please raise an issue at: https://github.com/Apadmi-Engineering/mirage/issues

// ignore_for_file: invalid_use_of_internal_member, unused_element

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:riverpod/src/providers/async_notifier.dart' as _i1;
import 'dart:convert' as _i2;
import 'package:mockito/mockito.dart' as _i3;
import 'input.dart' as _i4;
import 'dart:async' as _i5;
import 'package:riverpod/src/framework.dart' as _i6;
import 'package:mockito/src/dummies.dart' as _i7;
import 'asset:flumepod/test/input.dart' as _i8;
import 'package:riverpod/misc.dart' as _i9;
import 'package:riverpod/riverpod.dart' as _i10;

// Flumepod generated mock of class [TestNotifier].
class MockTestNotifier
    extends _i1.$AsyncNotifier<(_i2.Codec<dynamic, dynamic>, String)>
    with _i3.Mock
    implements _i4.TestNotifier {
  MockTestNotifier(this.seedBuilder);

  _i5.FutureOr<(_i2.Codec<dynamic, dynamic>, String)> Function() seedBuilder;

  @override
  runBuild() {
    {
      final ref = this.ref as _i6.$Ref<
          _i6.AsyncValue<(_i2.Codec<dynamic, dynamic>, String)>,
          (_i2.Codec<dynamic, dynamic>, String)>;
      final element = ref.element as _i6.$ClassProviderElement<
          _i6.AnyNotifier<_i6.AsyncValue<(_i2.Codec<dynamic, dynamic>, String)>,
              (_i2.Codec<dynamic, dynamic>, String)>,
          _i6.AsyncValue<(_i2.Codec<dynamic, dynamic>, String)>,
          Object?,
          Object?>;
      return element.handleCreate(ref, build);
    }
  }

  @override
  _i5.FutureOr<(_i2.Codec<dynamic, dynamic>, String)> build() async {
    // keepAlive() used so mock instance with stubbed/real calls isn't disposed.
    ref.keepAlive();
    return noSuchMethod(Invocation.method(#build, []),
        returnValueForMissingStub: seedBuilder());
  }

  @override
  ({String a, String b}) someMethod() {
    return noSuchMethod(
      Invocation.method(#someMethod, []),
      returnValueForMissingStub: _i7.dummyValue<({String a, String b})>(
          this, Invocation.method(#someMethod, [])),
      returnValue: _i7.dummyValue<({String a, String b})>(
          this, Invocation.method(#someMethod, [])),
    );
  }

  @override
  _i5.Future<int> someAsyncMethod() async {
    return noSuchMethod(
      Invocation.method(#someAsyncMethod, []),
      returnValueForMissingStub:
          _i7.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
      returnValue:
          _i7.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
    );
  }

  @override
  void sideEffect() {
    return noSuchMethod(
      Invocation.method(#sideEffect, []),
    );
  }

  @override
  _i5.Future<void> asyncSideEffect() async {
    return noSuchMethod(
      Invocation.method(#asyncSideEffect, []),
    );
  }
}

extension MockTestNotifierAccessor on _i8.TestNotifierProvider {
  _i9.ProviderListenable<MockTestNotifier> get mock {
    return notifier.select((it) => it as MockTestNotifier);
  }
}
