// DO NOT MODIFY BY HAND! This file has been generated by mirage. If there is an issue with it please raise an issue at: https://github.com/Apadmi-Engineering/mirage/issues

// ignore_for_file: invalid_use_of_internal_member, unused_element

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:riverpod/src/providers/notifier.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'input.dart' as _i3;
import 'package:riverpod/src/framework.dart' as _i4;
import 'package:mockito/src/dummies.dart' as _i5;
import 'dart:async' as _i6;

// Mirage generated mock of class [TestNotifier].
class MockTestNotifier extends _i1.$Notifier<String>
    with _i2.Mock
    implements _i3.TestNotifier {
  MockTestNotifier(this.seedBuilder);

  String Function() seedBuilder;

  @override
  runBuild() {
    {
      final created = build();
      final ref = this.ref as _i4.$Ref<String, String>;
      final element = ref.element as _i4.$ClassProviderElement<
          _i4.AnyNotifier<String, String>, String, Object?, Object?>;
      element.handleValue(ref, created);
    }
  }

  @override
  String build() {
    return noSuchMethod(Invocation.method(#build, []),
        returnValueForMissingStub: seedBuilder());
  }

  @override
  String someMethod() {
    return noSuchMethod(
      Invocation.method(#someMethod, []),
      returnValueForMissingStub:
          _i5.dummyValue<String>(this, Invocation.method(#someMethod, [])),
      returnValue:
          _i5.dummyValue<String>(this, Invocation.method(#someMethod, [])),
    );
  }

  @override
  _i6.Future<int> someAsyncMethod() async {
    return noSuchMethod(
      Invocation.method(#someAsyncMethod, []),
      returnValueForMissingStub:
          _i5.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
      returnValue:
          _i5.dummyValue<int>(this, Invocation.method(#someAsyncMethod, [])),
    );
  }

  @override
  void sideEffect() {
    return noSuchMethod(
      Invocation.method(#sideEffect, []),
    );
  }

  @override
  _i6.Future<void> asyncSideEffect() async {
    return noSuchMethod(
      Invocation.method(#asyncSideEffect, []),
    );
  }
}
