name: Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 #v3.1.1
        with:
          app-id: ${{ secrets.MELOS_APP_ID }}
          private-key: ${{ secrets.MELOS_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - uses: kuhnroyal/flutter-fvm-config-action/setup@c378498f1d1962d33039c3989411093ef8a17b2c # v3.3.0
      - name: Download dependencies and execute code generation
        run: |
          flutter --version
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
      - name: Run unit tests
        run: |
          dart run test test/unit
      - name: Run integration tests
        run: |
          dart run build_runner test -- test/integration
      - name: Run golden tests
        run: |
          dart run build_runner test -- test/golden