name: Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - name: Download dependencies and execute code generation
        run: |
          flutter --version
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
      - name: Run unit tests
        run: |
          dart run test test/unit
      - name: Run golden tests
        run: |
          dart run build_runner test -- test/golden