name: Publish packages
on:
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 #v3.1.1
        with:
          app-id: ${{ secrets.MELOS_APP_ID }}
          private-key: ${{ secrets.MELOS_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - uses: bluefireteam/melos-action@705015c3d2bc4ab94201ac24accb2bbe070cf533 # v3.6.0
        with:
          publish: true
          environment: pub.dev